name: File Scanning Action
description: Scan files using a Python script
inputs:
  files:
    description: 'List of files to scan'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      python /app/vulnerabilities_scanner.py ${{ join(inputs.files, ' ') }}
  env:
    GITHUB_WORKSPACE: ${{ github.workspace }}
