name: File Scanning Action
description: Scan files using a Python script
inputs:
  files:
    description: 'List of files to scan'
    required: true
  workspace:
    description: 'GitHub workspace directory'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      files_args=$(echo '${{ toJson(inputs.files) }}' | python -c "import sys, json; print(' '.join(json.load(sys.stdin)))")
      python /app/vulnerabilities_scanner.py $files_args
