name: CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python tests/tester.py
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
    
    - name: Debug Information
      run: |
        echo "Exit status of tests: $?"
        echo "Current directory: $(pwd)"
        echo "Files in current directory: $(ls -a)"
        echo "GitHub workspace directory: $GITHUB_WORKSPACE"
    
    - name: Revert Push on Scan Failure
      if: failure()
      run: |
        git config --global user.name "Leon Detector Bot"
        git config --global user.email "actions@github.com"
        git log -n 1
        git revert HEAD --no-edit
        git push origin main
