name: CI

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List example files
      id: list-files
      run: |
        echo "::set-output name=files::$(find examples -type f)"

    - name: Run tests
      run: |
        for file in ${{ steps.list-files.outputs.files }}; do
          echo "Running tests for $file"
          python vulnerabilities_scanner.py "$file"
          exit_code=$?
          echo "Exit code for $file: $exit_code"
          if [ $exit_code -ne 1 ]; then
            echo "Vulnerability was not detected in $file"
          fi
        done
